In [69]:
import pandas as pd

In [70]:
table = pd.read_csv("pz4.csv", encoding='utf-8')
table.columns = ["Регион", *list(range(2003, 2020, 1))]
table

,Регион,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,#####,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,Ханты-Мансийский автономный округ - Югра (Тюме...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2228536.39,2040628.19,2465505.6,2720895.1,2954950.8,2515767.7,2442687,2264695.5,2089543.19,2282701.6
2,Ямало-Ненецкий автономный округ (Тюменская обл...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,724074.4,826791.3,942051,905200.6,871948.1,908662.89,1005690.2,1001489.7,1116225.6,1388261.4
3,Тюменская область (кроме Ханты-Мансийского авт...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,1398139.4,1646036.2,1642570.1,1689217.5,1940716.3,1861785.79,2432762.4,2537705.9
4,Республика Алтай,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123369.4,265508,269770.3,269770.3,425207.4,720724.6,1015143.3,624930.69,682875.7,851700.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,32401000000 Кемерово,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.79,86.87,87.41,89.75,89.39,89.07,87.68,86.09,85.62,87.91
140,32449000000 Юрга,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.5,84.74,85.85,87.46,84.76,83.55,82.82,82.55,84.4,86.41
141,50401000000 Новосибирск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.09,102.43,102.27,103.11,102.01,102.33,102,101.27,99.31,98.49
142,52401000000 Омск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.52,83.09,83.14,84.12,85.15,85.31,85.26,84.67,85.19,87.66
143,69401000000 Томск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.77,97.85,97.69,98.08,97.27,97.02,97.17,96.47,96.8,98.13

In [73]:
# Разбиение табличек

l = table.shape[0]
I = []

for num, row in enumerate(table["Регион"]):
    if row == "#####":
        I.append(num)
I.append(l + 1)

razb = []
for i in range(len(I) - 1):
    razb.append((I[i] + 1, I[i + 1] - 1))

print(razb)

[(1, 14), (16, 29), (31, 44), (46, 59), (61, 78), (80, 97), (99, 112), (114, 127), (129, 144)]

In [76]:
table.loc[razb[0][0]: razb[0][1]]

,Регион,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,Ханты-Мансийский автономный округ - Югра (Тюме...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2228536.39,2040628.19,2465505.6,2720895.1,2954950.8,2515767.7,2442687,2264695.5,2089543.19,2282701.6
2,Ямало-Ненецкий автономный округ (Тюменская обл...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,724074.4,826791.3,942051,905200.6,871948.1,908662.89,1005690.2,1001489.7,1116225.6,1388261.4
3,Тюменская область (кроме Ханты-Мансийского авт...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,1398139.4,1646036.2,1642570.1,1689217.5,1940716.3,1861785.79,2432762.4,2537705.9
4,Республика Алтай,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123369.4,265508,269770.3,269770.3,425207.4,720724.6,1015143.3,624930.69,682875.7,851700.69
5,Республика Бурятия,NaN,NaN,NaN,NaN,NaN,NaN,NaN,484863.1,598606.1,773250.8,791893.1,733217.6,733627.8,769151,711432.8,721899.3,825707.9
6,Республика Тыва,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72145.7,60273.7,74517,80108,81551.4,80778.7,71767.8,79734.7,91587.1,102238.6
7,Республика Хакасия,NaN,NaN,NaN,NaN,NaN,NaN,NaN,199672.2,240483.9,246157.7,220832,386540.4,433603,316888.1,389030.1,436645.69,428159.2
8,Алтайский край,NaN,NaN,NaN,NaN,NaN,NaN,NaN,725600.3,847640.3,927587.9,888997.7,927467.7,906521.7,1055559.6,1301872.39,1479714.4,1526298.6
9,Забайкальский край,NaN,NaN,NaN,NaN,NaN,NaN,NaN,388529.1,460323.1,860796.9,617958.1,642201.4,535659.3,645164.4,595405.1,658860.1,689552.4
10,Красноярский край,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1215284.4,1360547,1575651.7,1760334.49,1777793.29,1650461,2054491.79,2332009.6,2777702.4,2972394.2
11,Иркутская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1279836.5,1475211,1633443.39,1807069.9,1689557.2,1882464.6,2275275.9,2549259.6,2854936.6,3299993.2
12,Новосибирская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1184190.3,1572685.8,1955636.6,2365089.29,2344230.19,1782228.9,2771074.2,3117069.2,3376319.2,3793406.9
13,Омская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,452391.8,682851.5,886018.9,1041200.4,1070380.5,1108145.6,848321.3,920007.7,1202470.5,1279288.1
14,Томская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,473174.4,493720.7,501149.79,491025.7,417181.4,535920.4,705352.8,721877.7,747416.6,845138.1

In [77]:
t = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
t

   0  1  2
0  1  2  3
1  4  5  6